apiVersion: v1
kind: ConfigMap
metadata:
  name: booking-configmap
  namespace: sps-ns
data:
  PORT: "4003"
  CORS_ORIGIN: "*"
  PARKING_SERVICE_URL: "http://parking-service"
  NOTIFICATION_SERVICE_URL: "http://notification-service"
  BOOKING_HOLD_MINUTES: "10"

