apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smart-parking-frontend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/Nimesh-Capstone-Project/Smart-Parking-System.git
    targetRevision: master
    path: infra/helm
    helm:
      valueFiles:
        - values/frontend.yaml
      values: |
        namespace: smart-parking
        authService:
          enabled: false
        bookingService:
          enabled: false
        gatewayApi:
          gateway:
            enabled: false
          httpRoute:
            enabled: false
        mongo:
          enabled: false
        notificationService:
          enabled: false
        parkingService:
          enabled: false
        paymentService:
          enabled: false
        schedulerService:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: smart-parking
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
