apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
  namespace: sps-ns
data:
  PORT: "4001"
  JWT_EXPIRES_IN: "7d"
  CORS_ORIGIN: "*"
  SEED_ADMIN_EMAIL: "admin@parking.com"
  SEED_USER_EMAIL: "user@parking.com"

