apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-configmap
  namespace: sps-ns
data:
  PORT: "4004"
  CORS_ORIGIN: "*"
  BOOKING_SERVICE_URL: "http://booking-service"
  NOTIFICATION_SERVICE_URL: "http://notification-service"



