namespace: sps-ns
environment: ""

rollout:
  enabled: false

rolloutStrategy:
  default:
    steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 50
      - pause: {}
  dev:
    steps:
      - setWeight: 50
  prod:
    steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 50
      - pause: {}

authService:
  enabled: true
  configMap:
    name: auth-configmap
    data:
      PORT: "4001"
      JWT_EXPIRES_IN: "7d"
      CORS_ORIGIN: "*"
      SEED_ADMIN_EMAIL: "admin@parking.com"
      SEED_USER_EMAIL: "user@parking.com"
  secret:
    name: auth-secret
    type: Opaque
    data:
      MONGO_URI: "bW9uZ29kYjovL21vbmdvLXN2YzoyNzAxNy9hdXRoZGI="
      JWT_SECRET: "c21hcnRwYXJraW5nX3N1cGVyX3NlY3JldA=="
      SEED_ADMIN_PASSWORD: "QWRtaW5AMTIz"
      SEED_USER_PASSWORD: "VXNlckAxMjM="
  deployment:
    name: auth-deploy
    replicas: 2
    selectorLabels:
      app: sps-auth
    podLabels:
      app: sps-auth
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1
    containers:
      - name: auth-container
        image:
          repository: nimeshsv814/auth-service
          tag: v1.0.0
        ports:
          - containerPort: 4001
        envFromConfigMaps:
          - auth-configmap
        envFromSecrets:
          - auth-secret
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
  service:
    name: auth-service
    selectorLabels:
      app: sps-auth
    ports:
      - port: 80
        targetPort: 4001
    type: ClusterIP

bookingService:
  enabled: true
  configMap:
    name: booking-configmap
    data:
      PORT: "4003"
      CORS_ORIGIN: "*"
      PARKING_SERVICE_URL: "http://parking-service"
      NOTIFICATION_SERVICE_URL: "http://notification-service"
      BOOKING_HOLD_MINUTES: "10"
  secret:
    name: booking-secret
    type: Opaque
    data:
      MONGO_URI: "bW9uZ29kYjovL21vbmdvLXN2YzoyNzAxNy9ib29raW5nZGI="
      JWT_SECRET: "c21hcnRwYXJraW5nX3N1cGVyX3NlY3JldA=="
      INTERNAL_API_KEY: "c21hcnRwYXJraW5nX2ludGVybmFsX2tleQ=="
  deployment:
    name: booking-deploy
    replicas: 2
    selectorLabels:
      app: sps-booking
    podLabels:
      app: sps-booking
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1
    containers:
      - name: booking-container
        image:
          repository: nimeshsv814/booking-service
          tag: v1.0.0
        ports:
          - containerPort: 4003
        envFromConfigMaps:
          - booking-configmap
        envFromSecrets:
          - booking-secret
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
  service:
    name: booking-service
    selectorLabels:
      app: sps-booking
    ports:
      - port: 80
        targetPort: 4003
    type: ClusterIP

frontend:
  enabled: true
  configMap:
    name: frontend-configmap
    data:
      VITE_AUTH_SERVICE_URL: "/auth"
      VITE_PARKING_SERVICE_URL: "/parking"
      VITE_BOOKING_SERVICE_URL: "/booking"
      VITE_PAYMENT_SERVICE_URL: "/payment"
      VITE_NOTIFICATION_SERVICE_URL: "/notification"
  secret:
    name: frontend-secret
    type: Opaque
    data:
      VITE_RAZORPAY_KEY_ID: "cnpwX3Rlc3RfU2hGRk14YTlKa3FtWnU="
  deployment:
    name: frontend-deploy
    replicas: 2
    selectorLabels:
      app: sps-frontend
    podLabels:
      app: sps-frontend
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1
    containers:
      - name: frontend-container
        image:
          repository: nimeshsv814/frontend
          tag: v1.1.3
        ports:
          - containerPort: 80
        envFromConfigMaps:
          - frontend-configmap
        envFromSecrets:
          - frontend-secret
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
  service:
    name: frontend-svc
    selectorLabels:
      app: sps-frontend
    ports:
      - port: 80
        targetPort: 80
    type: ClusterIP

gatewayApi:
  gateway:
    enabled: true
    name: sps-gateway
    gatewayClassName: kgateway
    listeners:
      - name: http
        protocol: HTTP
        port: 80
        allowedRoutes:
          namespaces:
            from: Same
  httpRoute:
    enabled: true
    name: sps-route
    parentRefs:
      - name: sps-gateway
        sectionName: http
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /auth
        filters:
          - type: URLRewrite
            urlRewrite:
              path:
                type: ReplacePrefixMatch
                replacePrefixMatch: /
        backendRefs:
          - name: auth-service
            port: 80
      - matches:
          - path:
              type: PathPrefix
              value: /parking
        filters:
          - type: URLRewrite
            urlRewrite:
              path:
                type: ReplacePrefixMatch
                replacePrefixMatch: /
        backendRefs:
          - name: parking-service
            port: 80
      - matches:
          - path:
              type: PathPrefix
              value: /booking
        filters:
          - type: URLRewrite
            urlRewrite:
              path:
                type: ReplacePrefixMatch
                replacePrefixMatch: /
        backendRefs:
          - name: booking-service
            port: 80
      - matches:
          - path:
              type: PathPrefix
              value: /payment
        filters:
          - type: URLRewrite
            urlRewrite:
              path:
                type: ReplacePrefixMatch
                replacePrefixMatch: /
        backendRefs:
          - name: payment-service
            port: 80
      - matches:
          - path:
              type: PathPrefix
              value: /notification
        filters:
          - type: URLRewrite
            urlRewrite:
              path:
                type: ReplacePrefixMatch
                replacePrefixMatch: /
        backendRefs:
          - name: notification-service
            port: 80
      - matches:
          - path:
              type: PathPrefix
              value: /
        backendRefs:
          - name: frontend-svc
            port: 80

mongo:
  enabled: true
  storageClass:
    enabled: true
    name: storage
    provisioner: nfs.csi.k8s.io
    parameters:
      server: 172.31.28.137
      share: /var/nfs/general/Smart-Parking
  statefulSet:
    name: mongo-deploy
    replicas: 2
    minReadySeconds: 10
    selectorLabels:
      app: sps-mongo
    podLabels:
      app: sps-mongo
    terminationGracePeriodSeconds: 10
    containers:
      - name: mongodb-cont
        image:
          repository: mongo
          tag: ""
        ports:
          - containerPort: 27017
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
        volumeMounts:
          - name: mongo-vct
            mountPath: /data/db
    volumeClaimTemplates:
      - metadata:
          name: mongo-vct
        spec:
          accessModes:
            - ReadWriteMany
          storageClassName: storage
          resources:
            requests:
              storage: 2Gi
  service:
    name: mongo-svc
    selectorLabels:
      app: sps-mongo
    ports:
      - port: 27017
        targetPort: 27017
    type: ClusterIP
    clusterIP: None

notificationService:
  enabled: true
  configMap:
    name: notification-configmap
    data:
      PORT: "4006"
      CORS_ORIGIN: "*"
  secret:
    name: notification-secret
    type: Opaque
    data:
      MONGO_URI: "bW9uZ29kYjovL21vbmdvLXN2YzoyNzAxNy9ub3RpZmljYXRpb25kYg=="
      JWT_SECRET: "c21hcnRwYXJraW5nX3N1cGVyX3NlY3JldA=="
      INTERNAL_API_KEY: "c21hcnRwYXJraW5nX2ludGVybmFsX2tleQ=="
  deployment:
    name: notification-deploy
    replicas: 2
    selectorLabels:
      app: sps-notification
    podLabels:
      app: sps-notification
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1
    containers:
      - name: notification-container
        image:
          repository: nimeshsv814/notification-service
          tag: v1.0.0
        ports:
          - containerPort: 4006
        envFromConfigMaps:
          - notification-configmap
        envFromSecrets:
          - notification-secret
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
  service:
    name: notification-service
    selectorLabels:
      app: sps-notification
    ports:
      - port: 80
        targetPort: 4006
    type: ClusterIP

parkingService:
  enabled: true
  configMap:
    name: parking-configmap
    data:
      PORT: "4002"
      CORS_ORIGIN: "*"
  secret:
    name: parking-secret
    type: Opaque
    data:
      MONGO_URI: "bW9uZ29kYjovL21vbmdvLXN2YzoyNzAxNy9wYXJraW5nZGI="
      JWT_SECRET: "c21hcnRwYXJraW5nX3N1cGVyX3NlY3JldA=="
      INTERNAL_API_KEY: "c21hcnRwYXJraW5nX2ludGVybmFsX2tleQ=="
  deployment:
    name: parking-deploy
    replicas: 2
    selectorLabels:
      app: sps-parking
    podLabels:
      app: sps-parking
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1
    containers:
      - name: parking-container
        image:
          repository: nimeshsv814/parking-service
          tag: v1.0.0
        ports:
          - containerPort: 4002
        envFromConfigMaps:
          - parking-configmap
        envFromSecrets:
          - parking-secret
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
  service:
    name: parking-service
    selectorLabels:
      app: sps-parking
    ports:
      - port: 80
        targetPort: 4002
    type: ClusterIP

paymentService:
  enabled: true
  configMap:
    name: payment-configmap
    data:
      PORT: "4004"
      CORS_ORIGIN: "*"
      BOOKING_SERVICE_URL: "http://booking-service"
      NOTIFICATION_SERVICE_URL: "http://notification-service"
  secret:
    name: payment-secret
    type: Opaque
    data:
      MONGO_URI: "bW9uZ29kYjovL21vbmdvLXN2YzoyNzAxNy9wYXltZW50ZGI="
      JWT_SECRET: "c21hcnRwYXJraW5nX3N1cGVyX3NlY3JldA=="
      INTERNAL_API_KEY: "c21hcnRwYXJraW5nX2ludGVybmFsX2tleQ=="
      RAZORPAY_KEY_ID: "cnpwX3Rlc3RfU2hGRk14YTlKa3FtWnU="
      RAZORPAY_KEY_SECRET: "MUk0c0xWSXZDTVdTVFVsTTVsQ1ptNzFq"
  deployment:
    name: payment-deploy
    replicas: 2
    selectorLabels:
      app: sps-payment
    podLabels:
      app: sps-payment
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1
    containers:
      - name: payment-container
        image:
          repository: nimeshsv814/payment-service
          tag: v1.0.1
        ports:
          - containerPort: 4004
        envFromConfigMaps:
          - payment-configmap
        envFromSecrets:
          - payment-secret
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
  service:
    name: payment-service
    selectorLabels:
      app: sps-payment
    ports:
      - port: 80
        targetPort: 4004
    type: ClusterIP

schedulerService:
  enabled: true
  configMap:
    name: scheduler-configmap
    data:
      PORT: "4005"
      BOOKING_SERVICE_URL: "http://booking-service"
      CRON_SCHEDULE: "* * * * *"
  secret:
    name: scheduler-secret
    type: Opaque
    data:
      INTERNAL_API_KEY: "c21hcnRwYXJraW5nX2ludGVybmFsX2tleQ=="
  deployment:
    name: scheduler-deploy
    replicas: 2
    selectorLabels:
      app: sps-scheduler
    podLabels:
      app: sps-scheduler
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1
    containers:
      - name: scheduler-container
        image:
          repository: nimeshsv814/scheduler-service
          tag: v1.0.0
        ports:
          - containerPort: 4005
        envFromConfigMaps:
          - scheduler-configmap
        envFromSecrets:
          - scheduler-secret
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
  service:
    name: scheduler-service
    selectorLabels:
      app: sps-scheduler
    ports:
      - port: 80
        targetPort: 4005
    type: ClusterIP
