apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smart-parking-dev-auth-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    ci.smartparking.io/last-built-sha: "7c8019f513aefd284842ca204e46c763f7e9ffbe"
    ci.smartparking.io/last-built-at: "2026-04-27T12:20:01Z"
    ci.smartparking.io/last-built-by: "nimeshsv814"
spec:
  project: default
  source:
    repoURL: https://github.com/Nimesh-Capstone-Project/Parking-System.git
    targetRevision: master
    path: infra/helm
    helm:
      valueFiles:
        - values/auth-service.yaml
      parameters:
        - name: authService.deployment.containers[0].image.repository
          value: ghcr.io/nimesh-capstone-project/auth-service
        - name: authService.deployment.containers[0].image.tag
          value: 7c8019f513aefd284842ca204e46c763f7e9ffbe
      values: |
        namespace: dev
        bookingService:
          enabled: false
        frontend:
          enabled: false
        gatewayApi:
          gateway:
            enabled: false
          httpRoute:
            enabled: false
        mongo:
          enabled: false
        notificationService:
          enabled: false
        parkingService:
          enabled: false
        paymentService:
          enabled: false
        schedulerService:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
