apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smart-parking-dev-booking-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    ci.smartparking.io/last-built-sha: "0765630c67ad40cb43139e8e6b01e723fe8de12f"
    ci.smartparking.io/last-built-at: "2026-04-27T13:05:55Z"
    ci.smartparking.io/last-built-by: "nimeshsv814"
spec:
  project: default
  source:
    repoURL: https://github.com/Nimesh-Capstone-Project/Parking-System.git
    targetRevision: master
    path: infra/helm
    helm:
      valueFiles:
        - values/booking-service.yaml
      parameters:
        - name: bookingService.deployment.containers[0].image.repository
          value: ghcr.io/nimesh-capstone-project/booking-service
        - name: bookingService.deployment.containers[0].image.tag
          value: 0765630c67ad40cb43139e8e6b01e723fe8de12f
      values: |
        namespace: dev
        authService:
          enabled: false
        frontend:
          enabled: false
        gatewayApi:
          gateway:
            enabled: false
          httpRoute:
            enabled: false
        mongo:
          enabled: false
        notificationService:
          enabled: false
        parkingService:
          enabled: false
        paymentService:
          enabled: false
        schedulerService:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
