apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smart-parking-dev-frontend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    ci.smartparking.io/last-built-sha: ""
    ci.smartparking.io/last-built-at: ""
    ci.smartparking.io/last-built-by: ""
spec:
  project: default
  source:
    repoURL: https://github.com/Nimesh-Capstone-Project/Parking-System.git
    targetRevision: master
    path: infra/helm
    helm:
      valueFiles:
        - values/frontend.yaml
      parameters:
        - name: frontend.deployment.containers[0].image.repository
          value: nimeshsv814/frontend
        - name: frontend.deployment.containers[0].image.tag
          value: v1.1.3
      values: |
        namespace: dev
        authService:
          enabled: false
        bookingService:
          enabled: false
        gatewayApi:
          gateway:
            enabled: false
          httpRoute:
            enabled: false
        mongo:
          enabled: false
        notificationService:
          enabled: false
        parkingService:
          enabled: false
        paymentService:
          enabled: false
        schedulerService:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

