apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smart-parking-dev-notification-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    ci.smartparking.io/last-built-sha: "dd67b9b353d45d7cac595a52b56189509648b92d"
    ci.smartparking.io/last-built-at: "2026-04-27T10:15:21Z"
    ci.smartparking.io/last-built-by: "nimeshsv814"
spec:
  project: default
  source:
    repoURL: https://github.com/Nimesh-Capstone-Project/Parking-System.git
    targetRevision: master
    path: infra/helm
    helm:
      valueFiles:
        - values/notification-service.yaml
      parameters:
        - name: notificationService.deployment.containers[0].image.repository
          value: ghcr.io/nimesh-capstone-project/notification-service
        - name: notificationService.deployment.containers[0].image.tag
          value: dd67b9b353d45d7cac595a52b56189509648b92d
      values: |
        namespace: dev
        authService:
          enabled: false
        bookingService:
          enabled: false
        frontend:
          enabled: false
        gatewayApi:
          gateway:
            enabled: false
          httpRoute:
            enabled: false
        mongo:
          enabled: false
        parkingService:
          enabled: false
        paymentService:
          enabled: false
        schedulerService:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
