apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smart-parking-dev-parking-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    ci.smartparking.io/last-built-sha: "a7b77a231ab72cd8b919e3c2024e2645f0d734f9"
    ci.smartparking.io/last-built-at: "2026-04-27T12:37:37Z"
    ci.smartparking.io/last-built-by: "nimeshsv814"
spec:
  project: default
  source:
    repoURL: https://github.com/Nimesh-Capstone-Project/Parking-System.git
    targetRevision: master
    path: infra/helm
    helm:
      valueFiles:
        - values/parking-service.yaml
      parameters:
        - name: parkingService.deployment.containers[0].image.repository
          value: ghcr.io/nimesh-capstone-project/parking-service
        - name: parkingService.deployment.containers[0].image.tag
          value: a7b77a231ab72cd8b919e3c2024e2645f0d734f9
      values: |
        namespace: dev
        authService:
          enabled: false
        bookingService:
          enabled: false
        frontend:
          enabled: false
        gatewayApi:
          gateway:
            enabled: false
          httpRoute:
            enabled: false
        mongo:
          enabled: false
        notificationService:
          enabled: false
        paymentService:
          enabled: false
        schedulerService:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
