apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smart-parking-dev-payment-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    ci.smartparking.io/last-built-sha: "3fcd0c697b805d726e2f297c89de1dbeff1212b3"
    ci.smartparking.io/last-built-at: "2026-04-27T12:55:02Z"
    ci.smartparking.io/last-built-by: "nimeshsv814"
spec:
  project: default
  source:
    repoURL: https://github.com/Nimesh-Capstone-Project/Parking-System.git
    targetRevision: master
    path: infra/helm
    helm:
      valueFiles:
        - values/payment-service.yaml
      parameters:
        - name: paymentService.deployment.containers[0].image.repository
          value: ghcr.io/nimesh-capstone-project/payment-service
        - name: paymentService.deployment.containers[0].image.tag
          value: 3fcd0c697b805d726e2f297c89de1dbeff1212b3
      values: |
        namespace: dev
        authService:
          enabled: false
        bookingService:
          enabled: false
        frontend:
          enabled: false
        gatewayApi:
          gateway:
            enabled: false
          httpRoute:
            enabled: false
        mongo:
          enabled: false
        notificationService:
          enabled: false
        parkingService:
          enabled: false
        schedulerService:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
