apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smart-parking-dev-scheduler-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    ci.smartparking.io/last-built-sha: "05ebf32b879331983629febe5d1cfb80b32c0736"
    ci.smartparking.io/last-built-at: "2026-04-27T12:59:20Z"
    ci.smartparking.io/last-built-by: "nimeshsv814"
spec:
  project: default
  source:
    repoURL: https://github.com/Nimesh-Capstone-Project/Parking-System.git
    targetRevision: master
    path: infra/helm
    helm:
      valueFiles:
        - values/scheduler-service.yaml
      parameters:
        - name: schedulerService.deployment.containers[0].image.repository
          value: ghcr.io/nimesh-capstone-project/scheduler-service
        - name: schedulerService.deployment.containers[0].image.tag
          value: 05ebf32b879331983629febe5d1cfb80b32c0736
      values: |
        namespace: dev
        authService:
          enabled: false
        bookingService:
          enabled: false
        frontend:
          enabled: false
        gatewayApi:
          gateway:
            enabled: false
          httpRoute:
            enabled: false
        mongo:
          enabled: false
        notificationService:
          enabled: false
        parkingService:
          enabled: false
        paymentService:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
