apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smart-parking-prod-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/Nimesh-Capstone-Project/Smart-Parking-System.git
    targetRevision: master
    path: infra/helm
    helm:
      valueFiles:
        - values/gateway.yaml
      values: |
        namespace: prod
        authService:
          enabled: false
        bookingService:
          enabled: false
        frontend:
          enabled: false
        mongo:
          enabled: false
        notificationService:
          enabled: false
        parkingService:
          enabled: false
        paymentService:
          enabled: false
        schedulerService:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

