apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smart-parking-prod-notification-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    ci.smartparking.io/last-release-sha: ""
    ci.smartparking.io/last-release-tag: ""
    ci.smartparking.io/last-released-at: ""
    ci.smartparking.io/last-released-by: ""
spec:
  project: default
  source:
    repoURL: https://github.com/Nimesh-Capstone-Project/Parking-System.git
    targetRevision: master
    path: infra/helm
    helm:
      valueFiles:
        - values/notification-service.yaml
      parameters:
        - name: notificationService.deployment.containers[0].image.repository
          value: nimeshsv814/notification-service
        - name: notificationService.deployment.containers[0].image.tag
          value: v1.0.0
      values: |
        namespace: prod
        authService:
          enabled: false
        bookingService:
          enabled: false
        frontend:
          enabled: false
        gatewayApi:
          gateway:
            enabled: false
          httpRoute:
            enabled: false
        mongo:
          enabled: false
        parkingService:
          enabled: false
        paymentService:
          enabled: false
        schedulerService:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

